Use 1 instead of true, to avoid errors with new AVRs.
csdexter/RDA5807M pull request #6
Opened 2020-01-24 05:57 UTC by veganism

Using any of the new 0 or 1-series chips (at least with [megaTinyCore](https://github.com/SpenceKonde/megaTinyCore)) with Wire.requestFrom using "true" instead of "1" for the bool will throw a huge fit and not compile, complaining that it's too ambiguous.
I don't entirely understand the issue, but [here](https://forum.arduino.cc/index.php?topic=623194.msg4314394#msg4314394) is a forum post referencing it.

In any case, I don't see how this change could hurt anything, and it allows the library to work with new chips.

2020-01-26 17:49 UTC, csdexter commented
Hello @veganism and thanks for your pull request!

The root of the problem resides in the Arduino IDE/Core authors (sadly and regrettably) not being very proficient in C++. `Wire::requestFrom()` is not an isolated example, the whole AVR Core (runtime library, if you will) is sprinkled with cases of either abusing C++ concepts or plain old missing the point of language features.

In the particular case of `Wire::requestFrom()`, the _faux pas_ involved is superfluous overloads (they defined far more versions of the method than strictly needed, no less than 5 in this case, thus causing the compiler to shrug and go "_well, which one you want, actually?_"). Note that (1) this has absolutely no connection with the actual AVR CPU we're compiling for and (2) (once again sadly and regrettably) authors of other Arduino Cores, for alternative boards (e.g. ARM-based ones), are more than likely to have copy/pasted the existing API verbatim which means the issue persists even far away from the original Arduino codebase.

The fact that the authors of other Arduino Cores (be they alternates for the original one, targeting different AVRs or even ARM-based boards) sometimes change the API in subtle ways (such as this very case), doesn't help the situation either.

The method is [documented in the official reference](https://www.arduino.cc/en/Reference/WireRequestFrom) as taking a `bool` argument, so I oppose the idea of replacing `true` with `1`, for reasons of coding style. I am however open to typecasting the 2nd argument to `size_t` for the first two occurrences of the call, as it most closely matches the design intent of both libraries involved. The third occurrence doesn't need a fix because the return type of `sizeof()` is already `size_t`.

I have just tested this version and it compiles fine with both the original Arduino Core (for AVR and megaAVR) and megaTinyCore.

Please let me know if you'd rather update your pull request (and have me merge it), or have me perform the changes and credit you in the `README` file instead.

Thank you for your submission and have a nice day!

2020-01-27 23:16 UTC, veganism commented
Thank you for your incredibly thorough explanation of what's going on, it makes a lot more sense now. I'm still a beginner when it comes to Arduino and _definitely_ a beginner when it comes to C/C++, so I'm impressed that I managed to stumble onto a band-aid fix with some dumb luck. I've tested the changes you suggested and they appear to work for me as well, so I'll close this request and open a new one shortly.

I'm happy to have contributed, even in such a small way.

2020-01-28 00:03 UTC, veganism commented
Hopefully I picked the correct style of type casting (based on other casts in the code?). If not, go ahead and fix everything as you see fit. I'm still learning. :stuck_out_tongue:

2020-01-28 08:22 UTC, csdexter requested changes
The form looks good and is consistent with the rest of the code, however you should be casting to `size_t`, not pointer to `size_t` (change `(size_t *)` to `(size_t)`). With that change made, this pull request is good to be merged and I'll do so ASAP.

2020-01-28 16:32 UTC, csdexter requested changes
Sorry, Murphy's Law strikes again, my bad. The second argument should be typecast, not the third. So the `(size_t)` should apply to the value `2` (first call) and `count * 2` expression (second call). This also means you need to add parentheses around the `count * 2` for the typecast to apply to it as a whole.

I apologize for not spotting this the first time over.

2020-01-28 18:14 UTC, veganism commented
Thank you for bearing with me as I figure this out. Ironically, it's still entirely ambiguous to me, but I'm learning things the hard way at least. The cores and compilers are so forgiving that just about every thing that I've tried has "worked" (in that it compiled successfully), regardless of the pointer / type, and even which argument I changed... so rather hopelessly, I keep committing errors. Throw in that there are varying _styles_ of type casting, for instance having `size_t(count * 2)` or `(size_t)(count * 2)` or even the other methods I saw for C++ specifically, like the odd (to me): `static_cast<size_t>(count * 2)`, well it's enough to make anybody confused.

Anyways, hopefully third time is a charm.

2020-01-28 22:33 UTC, csdexter approved these changes
This is now perfect, thank **you** for bearing with me on this one :)

2020-01-28 22:50 UTC, csdexter commented
In languages like C and C++ some (arguably wrong) stuff will appear to "just work" (or at least compile) mostly because human-wrong and compiler-wrong are different kinds of "wrong" :)
Normally, using a pointer (to the value) instead of a value should not compile (because the two cannot be [implicitly converted](https://en.cppreference.com/w/cpp/language/implicit_conversion) between), but then if the library author worked their magic and one of the overloads **does** take a pointer as an argument, then this rule won't protect you anymore.

C++ officially supports both the C style of typecasting syntax and the C++-specific one. The main difference is in flexibility: in C, you can only tell the compiler "_treat X as Y because I said so!_”. If you (the human) got that wrong, the compiler won't know (won't even try to find out) and you're on your own if something later breaks. With the C++ style you can ask the compiler to perform varying degrees of checks on the typecast, so that you get a compile or runtime error if things look fishy with that conversion.
I personally favor the C-style of typecast in embedded environments (like the Arduino) because in those cases I actually want the C-style behaviour. If I were coding for an API (not a chip), I'd use the C++ style because I'd want the extra checks.

Good luck with your endeavour in programming!

2020-01-28 22:52 UTC, merged